### ISSUE TITLE
Fix CI: CI does not use the promised Rust version

### ISSUE THREAD

**Issue by phip1611** [rust-osdev/multiboot2#107]
By experiments, I found out that the [current Github CI](https://github.com/rust-osdev/multiboot2/blob/76a3d2e1a9d718095d48cb0aa7cf08dc8ba4559a/.github/workflows/rust.yml) does not use the specified Rust version. I could verify this by using "1.30.0", an old version that definitely does not work.

Minimal Reproducible Example
```yml
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        rust:
          - 1.30.0 # MSVR
    steps:
      - uses: actions/checkout@v2
      - run: cargo --version
      - uses: actions-rs/cargo@v1
        with:
          command: version
```

Both commands return `1.60.0` which is the current latest stable version.
